name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
      - success
  workflow_dispatch:

jobs:
  build-test:
    name: Build 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifact from Payload CI pipeline
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: main.yml
        workflow_conclusion: success
        repo: ${{ github.repository }}
        if_no_artifact_found: fail

    - name: bash
      run: | 
        ls -la
        cd ./drop1
        ls -la
        
    - name: bash
      run: | 
        ls -la
        cd ./drop2
        ls -la
        
    - name: Set tar environment variable
      run: echo "tar=mytar1" >> $GITHUB_ENV

    - name: Use tar variable
      run: echo "The tar file is $tar"
