name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
      - success
  workflow_dispatch:
    inputs:
      auto_trigger:
        type: boolean
        description: Auto Trigger 
        default: true    
      build_workflow_run_id:
        type: string
        description: 'Build workflow run id (to retrieve artifacts)'
        required: true
        default: '-'  

        
jobs:
  build-test:
    name: Build 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifact from Payload CI pipeline
      if: ${{  github.event.inputs.auto_trigger == 'true' }}               
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: main.yml
        workflow_conclusion: success
        repo: ${{ github.repository }}
        if_no_artifact_found: fail

    - name: Download Build artifact
      if: ${{  github.event.inputs.auto_trigger == 'false' }}                   
      uses: actions/download-artifact@v4.1.0
      with:
        name: drop
        path: drop
        run-id: ${{ inputs.build_workflow_run_id }}
        github-token: ${{ github.token }}        

    - name: bash
      run: | 
        ls -la
        cd ./drop1
        ls -la
        
    - name: bash
      run: | 
        ls -la
        cd ./drop2
        ls -la
        
    - name: Set tar environment variable
      run: echo "tar=mytar1" >> $GITHUB_ENV

    - name: Use tar variable
      run: echo "The tar file is $tar"
