name: CI

on:
  workflow_dispatch:

jobs:
  build-test:
    name: Build 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop1
        path: |
           ./file1.txt
           
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop2
        path: |
           ./file2.txt           
           
    - name: Set custom value
      id: set_value
      run: echo "::set-output name=custom_value::dev"

    outputs:
      custom_value: ${{ steps.set_value.outputs.custom_value }}           
