name: CI

on:
  workflow_dispatch:

jobs:
  build-test:
    name: Build 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop1
        path: |
           ./file1.txt
           
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drop2
        path: |
           ./file2.txt           
      
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set version output
        id: set_version
        run: |
          VERSION="1.0.${{ github.run_number }}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=version::${VERSION}"

    outputs:
      version: ${{ steps.set_version.outputs.version }}  # Expose version as output

